server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/learn_db?currentSchema=payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
